import {
  User,
  Calendar as CalendarIcon,
  Heart,
  Target,
  Activity,
  Utensils,
  Scale,
  Moon,
  Bell,
  Check,
} from 'lucide-react-native';
import { OnboardingStep } from '@/types/onboarding';

export const onboardingSteps: OnboardingStep[] = [
  {
    id: 'welcome',
    title: 'Welcome to Aurae',
    subtitle: "Let's create your personalized wellness experience",
    icon: Heart,
    color: '#EC4899',
  },
  {
    id: 'personal',
    title: 'What should we call you?',
    subtitle: 'Your wellness journey starts with your name',
    icon: User,
    color: '#8B5CF6',
  },
  {
    id: 'birthday',
    title: 'When is your special day?',
    subtitle: 'Age matters for your hormones & metabolism',
    icon: CalendarIcon,
    color: '#10B981',
  },

  {
    id: 'fitness-goal',
    title: "What's your fitness goal?",
    subtitle: 'Choose your primary focus area',
    icon: Target,
    color: '#EF4444',
  },
  {
    id: 'fitness-frequency',
    title: 'How often do you work out?',
    subtitle: 'This helps us plan your weekly routine',
    icon: Activity,
    color: '#8B5CF6',
  },
  {
    id: 'fitness-experience',
    title: "What's your fitness experience?",
    subtitle: "We'll adjust the intensity accordingly",
    icon: Target,
    color: '#10B981',
  },
  {
    id: 'nutrition-goal',
    title: "What's your nutrition goal?",
    subtitle: 'This will help us customize your targets',
    icon: Utensils,
    color: '#10B981',
  },
  {
    id: 'nutrition-activity',
    title: 'How active are you?',
    subtitle: 'This affects your daily calorie needs',
    icon: Activity,
    color: '#F59E0B',
  },
  {
    id: 'nutrition-experience',
    title: 'Nutrition tracking experience?',
    subtitle: "We'll adjust the complexity for you",
    icon: Utensils,
    color: '#EC4899',
  },
  {
    id: 'body-units',
    title: 'Preferred units?',
    subtitle: 'Choose your measurement system',
    icon: Scale,
    color: '#6366F1',
  },
  {
    id: 'body-measurements',
    title: 'Your body measurements',
    subtitle: 'For precise calorie calculations',
    icon: Scale,
    color: '#F59E0B',
  },
  {
    id: 'complete',
    title: "You're all set!",
    subtitle: 'Ready to start your wellness journey',
    icon: Check,
    color: '#10B981',
  },
];
