export const queryKeys = {
  accounts: {
    all: ['accounts'] as const,
    detail: () => [...queryKeys.accounts.all, 'detail'] as const,
    subscription: () => [...queryKeys.accounts.all, 'subscription'] as const,
  },
  debts: {
    all: ['debts'] as const,
    list: (search?: string) => [...queryKeys.debts.all, 'list', search] as const,
    detail: (id: string) => [...queryKeys.debts.all, 'detail', id] as const,
    summary: () => [...queryKeys.debts.all, 'summary'] as const,
    payments: (debtId: string) => [...queryKeys.debts.all, 'payments', debtId] as const,
  },
  subscription: {
    all: ['subscription'] as const,
    info: (userId?: string) => [...queryKeys.subscription.all, 'info', userId] as const,
    status: () => [...queryKeys.subscription.all, 'status'] as const,
  },
  settings: {
    all: ['settings'] as const,
    detail: () => [...queryKeys.settings.all, 'detail'] as const,
    avatar: () => [...queryKeys.settings.all, 'avatar'] as const,
    weightHistory: (limit?: number) =>
      [...queryKeys.settings.all, 'weight-history', limit] as const,
    fitnessGoals: () => [...queryKeys.settings.all, 'fitness-goals'] as const,
    nutritionGoals: () => [...queryKeys.settings.all, 'nutrition-goals'] as const,
    weightGoals: () => [...queryKeys.settings.all, 'weight-goals'] as const,
    reminderSettings: ['settings', 'reminder-settings'] as const,
  },
  logs: {
    all: ['logs'] as const,
    weightEntries: (limit?: number) => [...queryKeys.logs.all, 'weight-entries', limit] as const,
    mealEntries: ['logs', 'meal-entries'] as const,
    waterEntries: ['logs', 'water-entries'] as const,
    waterIntake: ['logs', 'water-intake'] as const,
    dailyNutrition: ['logs', 'daily-nutrition'] as const,
    nutritionProgress: ['logs', 'nutrition-progress'] as const,
    weeklyNutrition: ['logs', 'weekly-nutrition'] as const,
    nutritionStreak: ['logs', 'nutrition-streak'] as const,
    exerciseEntries: ['logs', 'exercise-entries'] as const,
    dailyExercise: ['logs', 'daily-exercise'] as const,
    exerciseProgress: ['logs', 'exercise-progress'] as const,
    exerciseStreak: ['logs', 'exercise-streak'] as const,
    loggedDates: ['logs', 'logged-dates'] as const,
    weeklyExercisePlans: ['logs', 'weekly-exercise-plans'] as const,
  },
  scans: {
    all: ['scans'] as const,
    list: (filter: string, sort: string, search?: string) =>
      [...queryKeys.scans.all, 'list', filter, sort, search] as const,
    detail: (id: string) => [...queryKeys.scans.all, 'detail', id] as const,
  },
  favorites: {
    all: ['favorites'] as const,
  },
  preview: {
    recent: () => queryKeys.scans.list('recent', 'newest'),
    favorites: () => queryKeys.scans.list('favorites', 'newest'),
  },
  food: {
    all: ['food'] as const,
    search: ['food', 'search'] as const,
    byCategory: ['food', 'by-category'] as const,
    popular: ['food', 'popular'] as const,
  },
  exercise: {
    all: ['exercise'] as const,
    search: ['exercise', 'search'] as const,
    byCategory: ['exercise', 'by-category'] as const,
    byMuscleGroup: ['exercise', 'by-muscle-group'] as const,
    byEquipment: ['exercise', 'by-equipment'] as const,
    popular: ['exercise', 'popular'] as const,
  },
  progress: {
    all: ['progress'] as const,
    photos: (startDate: string, endDate: string) => [...queryKeys.progress.all, 'photos', startDate, endDate] as const,
  },
  nutrition: {
    all: ['nutrition'] as const,
    mealPlans: ['nutrition', 'meal-plans'] as const,
    groceryLists: ['nutrition', 'grocery-lists'] as const,
    favoriteFoods: ['nutrition', 'favorite-foods'] as const,
    dietaryPreferences: ['nutrition', 'dietary-preferences'] as const,
    existingIngredients: ['nutrition', 'existing-ingredients'] as const,
  },
  chat: {
    all: ['chat'] as const,
    messages: () => [...queryKeys.chat.all, 'messages'] as const,
  },
} as const;
