import type { ScanResult } from '@/lib/types/scan';

// Toggle this to enable/disable demo mode
export const DEMO_MODE = true;

// Local image imports for demo
export const DEMO_IMAGES = {
  yogurt: require('@/assets/images/demo-yogurt.png'),
  choco: require('@/assets/images/demo-choco.png'),
};

export const DEMO_SCANS: ScanResult[] = [
  // Pending scan at the top
  {
    id: 'demo-pending',
    user_id: 'demo-user',
    name: 'Analyzing...',
    image_url: 'local:choco',
    status: 'pending',
    summary: '',
    progress: 45,
    is_favorite: false,
    scanned_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-1',
    user_id: 'demo-user',
    name: 'Greek Yogurt with Berries',
    image_url: 'local:yogurt',
    status: 'safe',
    summary: 'Excellent choice for PCOS! High in protein, probiotics, and antioxidants with low glycemic impact.',
    ingredients: ['Greek yogurt', 'Blueberries', 'Strawberries', 'Chia seeds'],
    analysis: {
      glycemic_index: 'low',
      sugar_content: 'low',
      inflammatory_score: 2,
      hormone_impact: 'positive',
      fiber_content: 'moderate',
      protein_quality: 'high',
      healthy_fats: true,
      processed_level: 'minimally',
      recommendations: [
        'Great source of probiotics for gut health',
        'Berries provide antioxidants that reduce inflammation',
        'High protein helps with blood sugar control',
      ],
      warnings: [],
    },
    is_favorite: true,
    scanned_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(), // 30 mins ago
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'demo-2',
    user_id: 'demo-user',
    name: 'Chickee Eggs Vegan',
    image_url: 'local:choco',
    status: 'caution',
    summary: 'Vegan chocolate eggs - enjoy in moderation. While dairy-free, they still contain sugar that can affect blood sugar levels.',
    ingredients: ['Cocoa butter', 'Sugar', 'Cocoa powder', 'Rice milk powder', 'Vanilla', 'Soy lecithin'],
    analysis: {
      glycemic_index: 'medium',
      sugar_content: 'moderate',
      inflammatory_score: 4,
      hormone_impact: 'neutral',
      fiber_content: 'low',
      protein_quality: 'low',
      healthy_fats: true,
      processed_level: 'moderately',
      recommendations: [
        'Enjoy as an occasional treat in small portions',
        'Dark chocolate versions have more antioxidants',
        'Pair with nuts for better blood sugar response',
      ],
      warnings: [
        'Contains sugar that can spike blood sugar',
        'Limit to 1-2 pieces per serving',
      ],
    },
    is_favorite: false,
    scanned_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 hours ago
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 'demo-3',
    user_id: 'demo-user',
    name: 'Grilled Salmon',
    image_url: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400',
    status: 'safe',
    summary: 'Highly recommended for PCOS! Rich in omega-3 fatty acids that help reduce inflammation and support hormone balance.',
    ingredients: ['Atlantic salmon', 'Olive oil', 'Lemon', 'Garlic', 'Herbs'],
    analysis: {
      glycemic_index: 'low',
      sugar_content: 'low',
      inflammatory_score: 1,
      hormone_impact: 'positive',
      fiber_content: 'low',
      protein_quality: 'high',
      healthy_fats: true,
      processed_level: 'minimally',
      recommendations: [
        'Omega-3s help reduce inflammation',
        'High-quality protein supports muscle health',
        'Pair with vegetables for added fiber',
      ],
      warnings: [],
    },
    is_favorite: true,
    scanned_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // 1 day ago
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    id: 'demo-4',
    user_id: 'demo-user',
    name: 'White Rice',
    image_url: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=400',
    status: 'caution',
    summary: 'Consume in moderation. White rice has a high glycemic index but can be balanced with protein and vegetables.',
    ingredients: ['White rice'],
    analysis: {
      glycemic_index: 'high',
      sugar_content: 'low',
      inflammatory_score: 4,
      hormone_impact: 'neutral',
      fiber_content: 'low',
      protein_quality: 'low',
      healthy_fats: false,
      processed_level: 'moderately',
      recommendations: [
        'Consider switching to brown rice or quinoa',
        'Always pair with protein and healthy fats',
        'Keep portions small (1/2 cup)',
      ],
      warnings: [
        'High glycemic index may spike blood sugar',
        'Low in fiber compared to whole grains',
      ],
    },
    is_favorite: false,
    scanned_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(), // 2 days ago
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: 'demo-5',
    user_id: 'demo-user',
    name: 'Avocado Toast',
    image_url: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400',
    status: 'safe',
    summary: 'Great choice! Avocados provide healthy fats that support hormone production and reduce inflammation.',
    ingredients: ['Whole grain bread', 'Avocado', 'Olive oil', 'Sea salt', 'Red pepper flakes'],
    analysis: {
      glycemic_index: 'low',
      sugar_content: 'low',
      inflammatory_score: 2,
      hormone_impact: 'positive',
      fiber_content: 'high',
      protein_quality: 'moderate',
      healthy_fats: true,
      processed_level: 'minimally',
      recommendations: [
        'Add an egg for extra protein',
        'Use sprouted grain bread for better nutrition',
        'Great source of monounsaturated fats',
      ],
      warnings: [],
    },
    is_favorite: false,
    scanned_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(), // 3 days ago
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: 'demo-6',
    user_id: 'demo-user',
    name: 'Soda (Cola)',
    image_url: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400',
    status: 'avoid',
    summary: 'Strongly avoid. High sugar content and artificial ingredients can severely impact insulin resistance and hormone balance.',
    ingredients: ['Carbonated water', 'High fructose corn syrup', 'Caramel color', 'Phosphoric acid', 'Caffeine'],
    analysis: {
      glycemic_index: 'high',
      sugar_content: 'high',
      inflammatory_score: 9,
      hormone_impact: 'negative',
      fiber_content: 'low',
      protein_quality: 'low',
      healthy_fats: false,
      processed_level: 'highly',
      recommendations: [
        'Try sparkling water with lemon',
        'Herbal teas are a great alternative',
        'If craving sweetness, try stevia-sweetened drinks',
      ],
      warnings: [
        'Contains ~39g of sugar per can',
        'High fructose corn syrup worsens insulin resistance',
        'Caffeine may affect hormone levels',
        'No nutritional value',
      ],
    },
    is_favorite: false,
    scanned_at: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(), // 4 days ago
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
  },
  {
    id: 'demo-7',
    user_id: 'demo-user',
    name: 'Quinoa Bowl',
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
    status: 'safe',
    summary: 'Excellent PCOS-friendly meal! Complete protein with low glycemic index and high fiber content.',
    ingredients: ['Quinoa', 'Chickpeas', 'Cucumber', 'Tomatoes', 'Olive oil', 'Lemon'],
    analysis: {
      glycemic_index: 'low',
      sugar_content: 'low',
      inflammatory_score: 2,
      hormone_impact: 'positive',
      fiber_content: 'high',
      protein_quality: 'high',
      healthy_fats: true,
      processed_level: 'minimally',
      recommendations: [
        'Quinoa is a complete protein source',
        'High fiber helps stabilize blood sugar',
        'Add leafy greens for extra nutrients',
      ],
      warnings: [],
    },
    is_favorite: true,
    scanned_at: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(), // 5 days ago
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
  },
  {
    id: 'demo-8',
    user_id: 'demo-user',
    name: 'Fried Chicken',
    image_url: 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=400',
    status: 'avoid',
    summary: 'Best to avoid. Deep-fried foods increase inflammation and contain unhealthy trans fats.',
    ingredients: ['Chicken', 'Wheat flour', 'Vegetable oil', 'Salt', 'Spices'],
    analysis: {
      glycemic_index: 'medium',
      sugar_content: 'low',
      inflammatory_score: 8,
      hormone_impact: 'negative',
      fiber_content: 'low',
      protein_quality: 'moderate',
      healthy_fats: false,
      processed_level: 'highly',
      recommendations: [
        'Try air-fried or baked chicken instead',
        'Use almond flour coating for lower carbs',
        'Grilled chicken is a better option',
      ],
      warnings: [
        'Deep frying creates inflammatory compounds',
        'Breading adds refined carbohydrates',
        'Vegetable oils may worsen inflammation',
      ],
    },
    is_favorite: false,
    scanned_at: new Date(Date.now() - 1000 * 60 * 60 * 144).toISOString(), // 6 days ago
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 144).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 144).toISOString(),
  },
  {
    id: 'demo-9',
    user_id: 'demo-user',
    name: 'Mixed Nuts',
    image_url: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400',
    status: 'safe',
    summary: 'Great snack choice! Rich in healthy fats, protein, and minerals that support hormone balance.',
    ingredients: ['Almonds', 'Walnuts', 'Cashews', 'Pecans'],
    analysis: {
      glycemic_index: 'low',
      sugar_content: 'low',
      inflammatory_score: 1,
      hormone_impact: 'positive',
      fiber_content: 'moderate',
      protein_quality: 'high',
      healthy_fats: true,
      processed_level: 'minimally',
      recommendations: [
        'Walnuts are especially good for omega-3s',
        'Stick to a small handful (1oz) per serving',
        'Choose raw or dry-roasted without added oils',
      ],
      warnings: [],
    },
    is_favorite: false,
    scanned_at: new Date(Date.now() - 1000 * 60 * 60 * 168).toISOString(), // 7 days ago
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 168).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 168).toISOString(),
  },
  {
    id: 'demo-10',
    user_id: 'demo-user',
    name: 'Pasta Carbonara',
    image_url: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400',
    status: 'caution',
    summary: 'Enjoy occasionally in small portions. White pasta has high glycemic index but protein from eggs helps.',
    ingredients: ['Spaghetti', 'Eggs', 'Parmesan', 'Pancetta', 'Black pepper'],
    analysis: {
      glycemic_index: 'high',
      sugar_content: 'low',
      inflammatory_score: 5,
      hormone_impact: 'neutral',
      fiber_content: 'low',
      protein_quality: 'moderate',
      healthy_fats: false,
      processed_level: 'moderately',
      recommendations: [
        'Try chickpea or lentil pasta as alternative',
        'Add vegetables to increase fiber',
        'Keep portion size to 1/2 cup pasta',
      ],
      warnings: [
        'White pasta can spike blood sugar',
        'Processed meat may increase inflammation',
      ],
    },
    is_favorite: false,
    scanned_at: new Date(Date.now() - 1000 * 60 * 60 * 192).toISOString(), // 8 days ago
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 192).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 192).toISOString(),
  },
];

// Helper function to get a scan by ID
export function getDemoScanById(id: string): ScanResult | undefined {
  return DEMO_SCANS.find((scan) => scan.id === id);
}
